---
- name: Deploy Docker container on Ubuntu Server
  hosts: all
  gather_facts: false
  become: yes
  
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: 
        - docker

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
      tags: 
        - docker
        
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: rishavchandel/calculator:latest
        source: pull
        state: present
      tags: 
        - docker

    - name: Run Docker container
      docker_container:
        name: calculator
        image: rishavchandel/calculator:latest
        state: started
        restart_policy: always
        published_ports:
          - "8084:8080"
        container_default_behavior: "compatibility"
      tags: 
        - docker
