---
- name: Deploy Docker container on Ubuntu Server
  hosts: all
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: 
        - docker

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
      tags: 
        - docker
        
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: rishavchandel/calculator:latest
        source: pull
        state: present
        force_source: yes
      tags: 
        - docker

    - name: Check if process is listening on port 8086
      shell: "lsof -t -i:8086"
      register: pid_result
      ignore_errors: true
    
    - name: Kill process listening on port 8086
      shell: "kill -9 {{ pid_result.stdout }}"
      when: pid_result.rc == 0
    
    - name: Run Docker container
      docker_container:
        name: calculator
        image: rishavchandel/calculator:latest
        state: started
        restart_policy: always
        published_ports:
          - "8086:8080"
        container_default_behavior: "compatibility"
      ignore_errors: true
      register: docker_result
