---
- name: Deploy Docker container on Ubuntu VM
  hosts: all
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:    
    - name: Start Docker service
      service:
        name: docker
        state: started
    
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "rishavchandel/calculator"
        source: pull
    
    - name: Run Docker container
      docker_container:
        name: calculator_container
        image: "rishavchandel/calculator"
        state: started
        ports:
          - "8084:8080"
    
  
