---
- name: Deploy Docker container on Ubuntu Server
  hosts: all
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: 
        - docker

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
      tags: 
        - docker

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: rishavchandel/calculator
        source: pull
        state: present
        tag: latest
      tags: 
        - docker

    - name: Stop the existing container
      docker_container:
        name: calculator
        state: stopped
      register: stopped_container
      ignore_errors: yes  # Ignore errors if the container is not running

    - name: Remove the existing container
      docker_container:
        name: calculator
        state: absent
      when: stopped_container is success  # Only remove if the container was stopped successfully

    - name: Run Docker container
      docker_container:
        name: calculator
        image: rishavchandel/calculator:latest
        state: started
        restart_policy: always
        published_ports:
          - "8084:8080"
        container_default_behavior: "compatibility"
      tags: 
        - docker
